const GET_RECEPTIONS = 'GET_RECEPTIONS';
const GET_RECEPTIONS_SUCCESS = 'GET_RECEPTIONS_SUCCESS';
const GET_RECEPTIONS_ERROR = 'GET_RECEPTIONS_ERROR';
const ADD_RECEPTION = 'ADD_RECEPTION';
const ADD_RECEPTION_SUCCESS = 'ADD_RECEPTION_SUCCESS';
const ADD_RECEPTION_ERROR = 'ADD_RECEPTION_ERROR';
const EDIT_RECEPTION = 'EDIT_RECEPTION';
const EDIT_RECEPTION_SUCCESS = 'EDIT_RECEPTION_SUCCESS';
const EDIT_RECEPTION_ERROR = 'EDIT_RECEPTION_ERROR';
const DELETE_RECEPTION = 'DELETE_RECEPTION';
const DELETE_RECEPTION_SUCCESS = 'DELETE_RECEPTION_SUCCESS';
const DELETE_RECEPTION_ERROR = 'DELETE_RECEPTION_ERROR';

export { 
  GET_RECEPTIONS,
  GET_RECEPTIONS_SUCCESS,
  GET_RECEPTIONS_ERROR,
  ADD_RECEPTION,
  ADD_RECEPTION_SUCCESS,
  ADD_RECEPTION_ERROR,
  EDIT_RECEPTION,
  EDIT_RECEPTION_SUCCESS,
  EDIT_RECEPTION_ERROR,
  DELETE_RECEPTION,
  DELETE_RECEPTION_SUCCESS,
  DELETE_RECEPTION_ERROR,
};